site_name: ArchAiTect Workbench
site_url: https://docs.shafie.org
theme:
  name: material
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.tabs
  - navigation.top
nav:
- Home: index.md
- Projects: projects/index.md
markdown_extensions:
- admonition
- def_list
- footnotes
- toc:
    permalink: true
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.tabbed
- attr_list
- tables
plugins:
- search
- macros
- kroki: null
- exclude:
    glob:
    - package/**
    - architecture/**
    - catalog.md
    - services.md
    - srs.md
    - implementation-guide.md
extra_css:
- assets/extra.css
- assets/overrides.css
extra_javascript:
- assets/projects.js
extra:
  endpoints:
    workbench: https://workbench.shafie.org/
    openwebui: https://ai.shafie.org/
    kroki: https://kroki.shafie.org/
    plantuml: https://uml.shafie.org/
    docs: https://docs.shafie.org/
