site_name: ArchAiTect Workbench
site_url: https://docs.shafie.org

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
  - Services: services/index.md
  - Catalog: catalog/index.md
  - Diagrams:
      - Readme: diagrams/README.md
      - Booking Flow: diagrams/booking-sequence.md
      - Deployment: diagrams/deployment.md

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - tables

plugins:
  - search
  - macros
  - kroki:
  - exclude:
      glob:
        - "package/**"                     # drafts with unresolved links
        - "architecture/**"                # hide if you don’t want them yet
        - "catalog.md"
        - "services.md"
        - "srs.md"
        - "implementation-guide.md"

extra:
  endpoints:
    openwebui: https://ai.shafie.org/
    kroki: https://kroki.shafie.org/
    plantuml: https://uml.shafie.org/
