#!/usr/bin/env python3
# scripts/sync_projects.py
# Purpose: build-time sync of Workbench projects into MkDocs nav + index, without
# removing any other content.

import os, sys, json, pathlib, textwrap
from urllib.request import urlopen, Request
from urllib.error import URLError, HTTPError

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROJECTS_DIR = DOCS / "projects"
NAV_OUT = PROJECTS_DIR / "_nav.generated.yml"
INDEX_OUT = PROJECTS_DIR / "index.md"
CATALOG_OUT = DOCS / "catalog.md"

API_BASE = os.environ.get("WORKBENCH_API_BASE", "https://workbench.shafie.org").rstrip("/")

def fetch_projects():
    url = f"{API_BASE}/api/projects"
    try:
        with urlopen(Request(url, headers={"Accept": "application/json"}), timeout=10) as r:
            return json.loads(r.read().decode("utf-8"))
    except (URLError, HTTPError) as e:
        print(f"::warning::Failed to fetch {url}: {e}", file=sys.stderr)
        return []

def main():
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

    rows = fetch_projects()
    # sanitize + normalize
    api = [
        {"name": (r.get("name") or "").strip(), "slug": (r.get("slug") or "").strip()}
        for r in rows if r.get("slug")
    ]

    # Keep only those that actually have a docs landing page
    present = [
        p for p in api
        if (PROJECTS_DIR / p["slug"] / "index.md").exists()
    ]

    # 1) Write generated nav for Projects
    # Format is a short YAML fragment included by mkdocs.yml
    lines = []
    lines.append("# AUTOGENERATED. Do not edit by hand – updated by scripts/sync_projects.py\n")
    lines.append("- Projects:")
    lines.append("  - Overview: projects/index.md")
    for p in present:
        lines.append(f"  - {p['name']}: projects/{p['slug']}/index.md")
    NAV_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # 2) Write Projects overview page
    md = ["# Projects", ""]
    if not present:
        md.append("_No projects available right now._")
    else:
        for p in present:
            md.append(f"- [{p['name']}](/projects/{p['slug']}/)")
    INDEX_OUT.write_text("\n".join(md) + "\n", encoding="utf-8")

    # 3) Refresh simple catalog (kept from your previous behavior)
    projects_dirs = sorted(
        d.name for d in PROJECTS_DIR.iterdir() if d.is_dir()
    )
    cat = ["# Architecture Catalog", ""]
    for s in projects_dirs:
        md_page = DOCS / "packages" / f"{s}.md"
        if md_page.exists():
            cat.append(f"- [{s}](packages/{s}.md)")
    CATALOG_OUT.write_text("\n".join(cat) + "\n", encoding="utf-8")

    print(f"Synced {len(present)} projects into nav + index.")

if __name__ == "__main__":
    main()
