# server/services/mkdocs_nav.py

from pathlib import Path
from typing import Any, Dict, List

import yaml
from sqlmodel import select

from server.db import get_session
from server.models import Project

DOCS_ROOT = Path("docs")
PROJECTS_ROOT = DOCS_ROOT / "projects"
GENERATED_YAML = DOCS_ROOT / "_generated_projects_nav.yml"


def _ensure_docs_root() -> None:
    """Make sure the docs/projects tree exists."""
    PROJECTS_ROOT.mkdir(parents=True, exist_ok=True)


def _write_projects_index(projects: List[Project]) -> None:
    """
    Rewrite docs/projects/index.md so the MkDocs "Projects" page lists
    all projects and links to /projects/<slug>/.
    """
    lines: List[str] = [
        "# Projects",
        "",
        "These architecture projects are managed by the ArchAiTect Workbench:",
        "",
    ]

    if not projects:
        lines.append(
            "_No projects have been created yet via the Workbench UI._"
        )
    else:
        for p in projects:
            title = (p.nav_title or p.name).strip() if getattr(p, "nav_title", None) else p.name
            slug = p.slug
            lines.append(f"- [{title}](/projects/{slug}/)")

    lines.append("")
    (PROJECTS_ROOT / "index.md").write_text("\n".join(lines), encoding="utf-8")


def _write_generated_yaml(projects: List[Project]) -> None:
    """
    Write a small YAML summary that MkDocs macros can use if desired.

    Structure:
      projects:
        - slug: test-2
          title: "Test 2"
          url: "/projects/test-2/"
    """
    payload: Dict[str, Any] = {
        "projects": [
            {
                "slug": p.slug,
                "title": (p.nav_title or p.name).strip()
                if getattr(p, "nav_title", None)
                else p.name,
                "url": f"/projects/{p.slug}/",
            }
            for p in projects
        ]
    }
    GENERATED_YAML.write_text(
        yaml.safe_dump(payload, sort_keys=False), encoding="utf-8"
    )


def build_nav() -> None:
    """
    Synchronise MkDocs project navigation with the Workbench DB.

    - Ensures docs/projects/ exists.
    - Ensures docs/projects/<slug>/ directories exist (without overwriting
      any existing per-project index.md content generated by other tools).
    - Regenerates docs/projects/index.md so the /projects/ page lists all
      projects.
    - Writes docs/_generated_projects_nav.yml as a simple summary for
      MkDocs macros (optional consumer).

    This function is called from the FastAPI side whenever:
      - a project is created
      - a brief is saved
      - diagrams are generated

    It returns None; callers don’t rely on the return value.
    """
    _ensure_docs_root()

    with get_session() as session:
        projects: List[Project] = list(
            session.exec(select(Project).order_by(Project.created_at.asc()))
        )

    # Ensure a directory exists for each project, but do not overwrite any
    # existing index.md (that content is produced by the generators).
    for p in projects:
        project_dir = PROJECTS_ROOT / p.slug
        project_dir.mkdir(parents=True, exist_ok=True)

        index_md = project_dir / "index.md"
        if not index_md.exists():
            title = (p.nav_title or p.name).strip() if getattr(p, "nav_title", None) else p.name
            index_md.write_text(
                f"# {title}\n\n"
                "This project’s documentation is managed by the ArchAiTect Workbench.\n\n"
                "Once diagrams and docs are generated from the Workbench UI, "
                "they will appear here.\n",
                encoding="utf-8",
            )

    # Update projects overview page and YAML summary
    _write_projects_index(projects)
    _write_generated_yaml(projects)
